Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@juliocnsouzadev 
juliocnsouzadev
/
kubernetes-spring-boot-api-microservice-sample
Private
1
0
0
Code
Issues
1
Pull requests
Actions
Projects
Security
Insights
Settings
kubernetes-spring-boot-api-microservice-sample/.github/workflows/maven.yml
@juliocnsouzadev
juliocnsouzadev Update maven.yml
Latest commit c94c269 on 2 Jun
 History
 1 contributor
34 lines (28 sloc)  907 Bytes
  
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: juliocnsouza/spring-stackdriver${{ steps.tagName.outputs.version }}
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading complete
{"mode":"full","isActive":false}
